### ISSUE TITLE
Configure fails on Mac OS X 10.14

### ISSUE THREAD

**Issue by manthonyaiello** [persan/zeromq-Ada#15]
On Mac OS X 10.14, configure fails due to an error with the way the system-installed cpp processes system-provided headers. This is well documented on StackOverflow: https://stackoverflow.com/questions/42031921/unterminated-unconditional-directive-error-when-preprocessing-c-code.

A trivial fix for this problem is to not use `cpp` and instead to use `gcc -E` for the preprocessing step on line 63 of configure. Here's the whole whichzmq function:

```
def whichzmq():
    ret = "/usr"
    with file("_locate_zmq.c", "w") as outf:
        outf.write("#include <zmq.h>")
    response = subprocess.Popen(["gcc", "-E", "-pipe", "_locate_zmq.c"],
                                stdout=subprocess.PIPE).communicate()[0].split("\n")
    os.remove("_locate_zmq.c")
    for line in response:
        if "/zmq.h" in line:
            line = line.split('"')[1]
            ret = dirname(dirname(line))
    return ret

```

**Comment by persan** [comment]
Thanks for the note, Its implemented.
